apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
spec:
  deployment_type: openshift
  istio:
    authentication: true
    community: false
    prefix: openshift-istio-tech-preview/
    version: 0.4.0
  jaeger:
    prefix: distributed-tracing-tech-preview/
    version: 1.7.0
    elasticsearch_memory: 2Gi
  kiali:
    username: justin
    password: S@far123
    prefix: openshift-istio-tech-preview/
    version: 0.9.1
  launcher:
    openshift:
      user: justin
      password: S@far123
    github:
      username: justindav1s
      token: fffc440e529c23fdff144e0b9cf0b995573a2e86
    catalog:
      filter: booster.mission.metadata.istio
      branch: v71
      repo: https://github.com/fabric8-launcher/launcher-booster-catalog.git