apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install

  threeScale:
    enabled: false

  istio:
    global:
      hub: "registry.redhat.io/openshift-istio-tech-preview/"
      tag: 0.11.0
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 128Mi
      mtls: false
      disablePolicyChecks: true
      policyCheckFailOpen: true

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: false

    mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 10m
            memory: 1G
          limits:
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
      enabled: true
      hub: kiali/
      tag: v0.20.0
      dashboard:
        user: admin
        passphrase: admin
    tracing:
      enabled: false

    multitenant: false